f = open("/sd/gengar.wav", "rb")
header = f.read(44)
print("RIFF:", header[0:4])
print("Size:", int.from_bytes(header[4:8], "little"))
print("WAVE:", header[8:12])
print("Format:", int.from_bytes(header[20:22], "little"))
print("Channels:", int.from_bytes(header[22:24], "little"))
print("Sample Rate:", int.from_bytes(header[24:28], "little"))
print("Data pos:", int.from_bytes(header[40:44], "little"))
f.close()
